### ISSUE TITLE
About sam model‘s .pth file 

### ISSUE THREAD

**Issue by TVayne** [alibaba-damo-academy/samconvex#1]
Dear Zi LI：

It's an intersting work. I want to try in my experiment, it seems to require sam feature. So can you provide the weights file of the sam model?

Thank you!

**Comment by Alison-brie** [comment]
Hi, TVayne

Sorry for the late response. 

The model weights for SAM are provided in the SAM Repo (https://github.com/alibaba-damo-academy/self-supervised-anatomical-embedding-v2). 
You can use the SAM.pth or SAMv2_iter_20000.pth checkpoint.
